=== Nico-92/TecWeb/database/events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="eventi" >
	<xs:complexType>
		<xs:sequence>
			<xs:element name="evento" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>


						<xs:element name="nome" type="xs:string" />
						
						<xs:element name="data">
						  <xs:complexType>
						    <xs:sequence>

						    	<xs:element name="giorno" >
						      		<xs:simpleType>
								    	<xs:restriction base="xs:integer">
								        	<xs:minInclusive value="1" />
								        	<xs:maxInclusive value="31" />
								    	</xs:restriction>
							    	</xs:simpleType>
								</xs:element>

							    <xs:element name="mese" >
						      		<xs:simpleType>
							        	<xs:restriction base="xs:string">
							        		<xs:enumeration value="Gennaio" />
							        		<xs:enumeration value="Febbraio" />
							        		<xs:enumeration value="Marzo" />
							        		<xs:enumeration value="Aprile" />
							        		<xs:enumeration value="Maggio" />
							        		<xs:enumeration value="Giugno" />
							        		<xs:enumeration value="Luglio" />
							        		<xs:enumeration value="Agostoo" />
							        		<xs:enumeration value="Settembre" />
							        		<xs:enumeration value="Ottobre" />
							        		<xs:enumeration value="Novembre" />
							        		<xs:enumeration value="Dicembre" />
							        	</xs:restriction>
							    	</xs:simpleType>
								</xs:element>

							    <xs:element name="anno" >
						      		<xs:simpleType>
							        	<xs:restriction base="xs:integer">
							        		<xs:minInclusive value="2014" />
							       		</xs:restriction>
							    	</xs:simpleType>
								</xs:element>
						    
						    </xs:sequence>
						  </xs:complexType>
						</xs:element> 
						<xs:element name="descrizione" type="xs:string" />
						<xs:element name="menu">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="portata" type="xs:string" maxOccurs="unbounded" />
								</xs:sequence>
								<xs:attribute name="prezzo" type="xs:positiveInteger" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:positiveInteger" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Nico-92/TecWeb/database/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="events.xsd">
	
	<evento id="1">
		<nome>Pasqua</nome>
		<data>
			<giorno>20</giorno>
			<mese>Aprile</mese>
			<anno>2014</anno>
		</data>
		<descrizione>Cras tincidunt elit dolor, quis tempus enim lobortis ac. In iaculis tortor ut sem feugiat volutpat. Nunc volutpat augue metus, vitae condimentum odio varius et. Sed quis bibendum urna. Vivamus placerat id libero ut commodo. Praesent eu eros tortor. Praesent nisi libero, interdum nec suscipit sit amet, interdum sit amet eros.</descrizione>
		<menu prezzo="20">
			<portata>Fassone battuto al coltello</portata>
			<portata>Tacchino alla piastra</portata>
			<portata>Fetuccine al ragù di coniglio</portata>
		</menu>
	</evento>

	<evento id="2">
		<nome>Pasquetta</nome>
		<data>
			<giorno>21</giorno>
			<mese>Aprile</mese>
			<anno>2014</anno>
		</data>
		<descrizione>Cras tincidunt elit dolor, quis tempus enim lobortis ac. In iaculis tortor ut sem feugiat volutpat. Nunc volutpat augue metus, vitae condimentum odio varius et. Sed quis bibendum urna. Vivamus placerat id libero ut commodo. Praesent eu eros tortor. Praesent nisi libero, interdum nec suscipit sit amet, interdum sit amet eros.</descrizione>
		<menu prezzo="15">
			<portata>Fassone battuto al coltello</portata>
			<portata>Tacchino alla piastra</portata>
			<portata>Fetuccine al ragù di coniglio</portata>
		</menu>
	</evento>

	
 
		<evento id="3">
			<nome>Torte con Valeria</nome>
			<data>
				<giorno>17</giorno>
				<mese>Aprile</mese>
				<anno>2014</anno>
			</data>
			<descrizione>Cras tincidunt elit dolor, quis tempus enim lobortis ac. In iaculis tortor ut sem feugiat volutpat. Nunc volutpat augue metus, vitae condimentum odio varius et. Sed quis bibendum urna. Vivamus placerat id libero ut commodo. Praesent eu eros tortor. Praesent nisi libero, interdum nec suscipit sit amet, interdum sit amet eros.</descrizione>
			<menu price="32">
				<portata></portata>
				<portata>Tiramisù</portata>
				<portata>Torta Menta e cioccolato</portata>
				<portata>Semifreddi</portata>
				<portata>Cupcake</portata>
			</menu>
		</evento>
</eventi>
