=== Nico-92/TecWeb/database/log.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="log" >
	<xs:complexType>
		<xs:sequence>
			<xs:element name="item" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>


						<xs:element name="nome" type="xs:string" />
						<xs:element name="utente" type="xs:string" />
						
						<xs:element name="timestamp">
						<xs:complexType>
						<xs:sequence>
						<xs:element name="data">
						  <xs:complexType>
						    <xs:sequence>

						    	<xs:element name="giorno" >
						      		<xs:simpleType>
								    	<xs:restriction base="xs:integer">
								        	<xs:minInclusive value="1" />
								        	<xs:maxInclusive value="31" />
								    	</xs:restriction>
							    	</xs:simpleType>
								</xs:element>

							    <xs:element name="mese" >
						      		<xs:simpleType>
							        	<xs:restriction base="xs:string">
							        		<xs:enumeration value="Gennaio" />
							        		<xs:enumeration value="Febbraio" />
							        		<xs:enumeration value="Marzo" />
							        		<xs:enumeration value="Aprile" />
							        		<xs:enumeration value="Maggio" />
							        		<xs:enumeration value="Giugno" />
							        		<xs:enumeration value="Luglio" />
							        		<xs:enumeration value="Agostoo" />
							        		<xs:enumeration value="Settembre" />
							        		<xs:enumeration value="Ottobre" />
							        		<xs:enumeration value="Novembre" />
							        		<xs:enumeration value="Dicembre" />
							        	</xs:restriction>
							    	</xs:simpleType>
								</xs:element>

							    <xs:element name="anno" >
						      		<xs:simpleType>
							        	<xs:restriction base="xs:integer">
							        		<xs:minInclusive value="2014" />
							       		</xs:restriction>
							    	</xs:simpleType>
								</xs:element>

						    </xs:sequence>
						  </xs:complexType>
						</xs:element> 
						<!-- FINE DATA -->
						 <xs:element name="time" type="xs:time"/>
						</xs:sequence>
						</xs:complexType>
						</xs:element> 
						<!-- FINE TIMESTAMP -->
					</xs:sequence>
					<xs:attribute name="id" type="xs:positiveInteger" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Nico-92/TecWeb/database/log.xml
<?xml version="1.0" encoding="UTF-8"?>
<log xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="log.xsd">
	<item id="1">
		<nome>Inserita immagine</nome>
		<utente>defra91</utente>
		<timestamp>
			<data>
				<giorno>13</giorno>
				<mese>Marzo</mese>
				<anno>2014</anno>
			</data>
			<time>21:00:13</time>
		</timestamp>
	</item>

	<item id="2">
		<nome>Cancellato evento</nome>
		<utente>defra91</utente>
		<timestamp>
			<data>
				<giorno>20</giorno>
				<mese>Marzo</mese>
				<anno>2014</anno>
			</data>
			<time>16:14:21</time>
		</timestamp>
	</item>
</log>
