=== Nico-92/TecWeb/database/news.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="news" >
	<xs:complexType>
		<xs:sequence>
			
			<xs:element name="titolo" type="xs:string" />
			<xs:element name="descrizione" type="xs:string" />


			<xs:element name="data">
			  <xs:complexType>
			    <xs:sequence>

			    	<xs:element name="giorno" >
			      		<xs:simpleType>
					    	<xs:restriction base="xs:integer">
					        	<xs:minInclusive value="1" />
					        	<xs:maxInclusive value="31" />
					    	</xs:restriction>
				    	</xs:simpleType>
					</xs:element>

				    <xs:element name="mese" >
			      		<xs:simpleType>
				        	<xs:restriction base="xs:integer">
				        		<xs:minInclusive value="1" />
				        		<xs:maxInclusive value="12" />
				        	</xs:restriction>
				    	</xs:simpleType>
					</xs:element>

				    <xs:element name="anno" >
			      		<xs:simpleType>
				        	<xs:restriction base="xs:integer">
				        		<xs:minInclusive value="2014" />
				       		</xs:restriction>
				    	</xs:simpleType>
					</xs:element>
			    
			    </xs:sequence>
			  </xs:complexType>
			</xs:element> 

			<xs:element name="evento">
				<xs:complexType>
		   			<xs:simpleContent>
		        		<xs:extension base="xs:string">
		        			<xs:attribute name="id" type="xs:ipositiveInteger" use="required" />
		     			</xs:extension>
		    		</xs:simpleContent>
		  		</xs:complexType>	
			</xs:element> 

		</xs:sequence>
	</xs:complexType>

</xs:element>
</xs:schema>

=== Nico-92/TecWeb/database/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<news xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="news.xsd">
	
	<notizia id="2">
		<titolo>Lorem ipsum per tutti!!!</titolo>
		<descrizione>
			Donec posuere egestas blandit. Vestibulum ante urna, dignissim sit amet viverra sed, sollicitudin sit amet urna. Nulla nec nisl vel arcu tincidunt pulvinar porta id dolor. In hac habitasse platea dictumst. Nulla eleifend, ipsum quis viverra elementum, ligula urna dignissim mi, id aliquam purus purus in augue. Curabitur sit amet nunc vitae diam sagittis sollicitudin. Aliquam vestibulum quis orci sit amet euismod. Ut luctus suscipit urna. Suspendisse at auctor nisi, at consectetur mauris. Nullam vel tincidunt dui.
		</descrizione>
		<data>
		 	<giorno>24</giorno>
		 	<mese>Marzo</mese>
		 	<anno>2014</anno>
		 </data>
	</notizia>
	
	<notizia id="3">
		<titolo>Il sito è completato</titolo>
		<descrizione>Dopo un duro lavoro il sito è finalmente completo. </descrizione>
		<data>
			<giorno>25</giorno>
			<mese>Marzo</mese>
			<anno>2014</anno>
		</data>
	</notizia>
</news>
